Update lib to Angular v16 - bootstrap v5 - ngx-bootstrap v11
webcat12345/ngx-intl-tel-input pull request #497
Opened 2023-08-10 19:27 UTC by juju-sunrise

2023-10-10 17:34 UTC, AnwarMEQOR approved these changes

2024-09-22 07:51 UTC, TusharRoy23 commented
> Hi, can you check if this bug I reported a while ago is still in the code? #408 maybe you can fix this once for all 😁

Any updates?

2025-02-01 22:14 UTC, cmckni3 commented
> Hi, can you check if this bug I reported a while ago is still in the code? #408 maybe you can fix this once for all 😁

It probably is still an issue. I commented on #408

2025-02-01 22:14 UTC, cmckni3 commented
> Hi, can you check if this bug I reported a while ago is still in the code? #408 maybe you can fix this once for all 😁

@Kryger93  @TusharRoy23 It probably is still an issue. I commented on #408

2025-02-01 22:18 UTC, cmckni3 requested changes

2025-02-01 22:18 UTC, cmckni3 commented on .editorconfig
Revert change

2025-02-01 22:18 UTC, cmckni3 commented on .gitignore
> +.editorconfig
Revert change

2025-02-01 22:18 UTC, cmckni3 commented on README.md
>  | 2.x.x              | 8.x.x - 9.1.x  | 5.6.x         |
Revert all changes to this section of README

2025-02-01 22:18 UTC, cmckni3 commented on README.md
> -`$ npm install ngx-intl-tel-input --save`
Revert change

2025-02-01 22:18 UTC, cmckni3 commented on projects/ngx-intl-tel-input/package.json
> -		"url": "https://github.com/webcat12345/ngx-intl-tel-input/issues"
Revert change

2025-02-01 22:18 UTC, cmckni3 commented on projects/ngx-intl-tel-input/package.json
> -	"version": "3.3.0",
Revert change

2025-02-01 22:18 UTC, cmckni3 commented on projects/ngx-intl-tel-input/src/lib/ngx-intl-tel-input.component.html
Can you apply these changes in a separate PR?

2025-02-01 22:18 UTC, cmckni3 commented on projects/ngx-intl-tel-input/src/lib/ngx-intl-tel-input.component.css
Can you apply these changes in a separate PR?

2025-02-01 22:18 UTC, cmckni3 commented on projects/ngx-intl-tel-input/package.json
> -		"url": "git+https://github.com/webcat12345/ngx-intl-tel-input"
Revert change

2025-02-01 22:20 UTC, cmckni3 commented
Thanks for the contribution!

-----------

Please, update your branch with changes in `master` branch as fix conflicts as well.

I would recommend using a feature branch in your repo to create a PR from.

I can attempt to cherry pick your commits into a new branch.

2025-02-03 07:29 UTC, cmckni3 commented
> Thanks for the contribution @juju-sunrise!
> 
> Please, update your branch with changes in `master` branch as fix conflicts as well.
> 
> I would recommend using a feature branch in your repo to create a PR from.
> 
> I can attempt to cherry pick your commits into a new branch.

cherry-picked most of the changes to #545

2025-02-03 23:40 UTC, merged